### ISSUE TITLE
Question: why is assert required in test/sums-test.js?

### ISSUE THREAD

**Issue by adamkdean** [glennjones/be-more-hapi#9]
On [line four](https://github.com/glennjones/be-more-hapi/blob/master/test/sums-test.js#L4) of test/sums-test.js you require `assert` but then on line six, you're replacing this with `chai.assert`.

Is there a reason for this?

**Comment by glennjones** [comment]
Hi, yes `assert` was not needed. The code in the tests was very old, I had not kept it update. So I have updated the tests in the project so they work with the latest modules it is now using.

These days I do not use Mocha and Chai for Hapi projects, I use [Lab](https://github.com/hapijs/lab) and [Code](https://github.com/hapijs/code). Lab and Code add a few extras for Hapi development like linting to the code style guide for Hapi and code coverage reports.

Although Mocha and Chai are very good and still use them for other types of JS project.

Hope this information helps, if need anything else just ask.
